version: '3.8'

services: 
  node_backend:
    container_name: node_tabnine
    image: node_tabnine:0.0.4
    build: 
      context: .
    ports:
      - "3001:3001"
    environment: 
      - EXTERNAL_PORT=3001
      - PGDATABASE=tabnine_db
      - PGUSER=francesco
      - PGPASSWORD=12345
      - PGHOST=node_db
    depends_on: 
      - node_db
  node_db: 
    container_name: node_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=francesco
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=tabnine_db
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}

  
    